# Generated by Django 5.2.3 on 2025-06-18 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodInventory',
            fields=[
                ('bloodId', models.AutoField(primary_key=True, serialize=False)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=255)),
                ('quantity', models.IntegerField()),
                ('updated_on', models.DateField(auto_now=True)),
                ('expired_on', models.DateField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DonationCamp',
            fields=[
                ('campId', models.AutoField(primary_key=True, serialize=False)),
                ('camp_title', models.CharField(max_length=255)),
                ('camp_date', models.DateTimeField()),
                ('camp_location', models.CharField(max_length=255)),
                ('camp_city', models.CharField(max_length=255)),
                ('camp_state', models.CharField(max_length=255)),
                ('camp_pincode', models.CharField(max_length=255)),
                ('camp_organizer', models.CharField(max_length=255)),
                ('camp_organizer_phone', models.CharField(max_length=10)),
                ('camp_organizer_email', models.EmailField(max_length=255)),
                ('camp_organizer_address', models.CharField(max_length=255)),
                ('camp_organizer_city', models.CharField(max_length=255)),
                ('camp_organizer_state', models.CharField(max_length=255)),
                ('camp_organizer_pincode', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='DonorDetails',
            fields=[
                ('donerId', models.AutoField(primary_key=True, serialize=False)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('eligibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=255)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('donor', 'donor'), ('receiver', 'receiver')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TransfusionRecord',
            fields=[
                ('recordId', models.AutoField(primary_key=True, serialize=False)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=255)),
                ('quantity', models.IntegerField()),
                ('transfusion_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(max_length=255)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.donordetails')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userdetails')),
            ],
        ),
        migrations.AddField(
            model_name='donordetails',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userdetails'),
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('requestId', models.AutoField(primary_key=True, serialize=False)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=255)),
                ('quantity', models.IntegerField()),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('completed', 'completed')], default='pending', max_length=25)),
                ('patient_name', models.CharField(max_length=255)),
                ('hospital_name', models.CharField(max_length=255)),
                ('hospital_address', models.CharField(max_length=255)),
                ('hospital_city', models.CharField(max_length=255)),
                ('hospital_state', models.CharField(max_length=255)),
                ('hospital_pincode', models.CharField(max_length=255)),
                ('hospital_phone', models.CharField(max_length=255)),
                ('hospital_email', models.EmailField(max_length=255)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userdetails')),
            ],
        ),
    ]
